version: '3.8'

services:
  auth:
    image: aliahmed312/weatherapp-auth:latest
    container_name: weather-auth
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - mynetwork
    

  ui:
    image: aliahmed312/weatherapp-ui:latest
    container_name: weather-ui
    restart: always
    depends_on:
      - auth
      - weather
    environment:
        AUTH_HOST: auth
        AUTH_PORT: 8000
        WEATHER_HOST: weather
        WEATHER_PORT: 5000       
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    
  
  weather:
    image: aliahmed312/weatherapp-weather:latest
    container_name: weather-weather
    restart: always
    environment:
      APIKEY: ${APIKEY}
    ports:
      - "5000:5000"
    networks:
      - mynetwork 
       

  db:
    image: mysql
    container_name: weather-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - mynetwork
    volumes:
      - ./database:/var/lib/mysql
    
networks:
  mynetwork:
    driver: bridge

volumes:
  database: 
