apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  labels:
    app: mysql
spec:
  clusterIP: None  # This makes the service headless
  selector:
    app: mysql
  ports:
  - port: 3306
    
