apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-weather
  labels:
    app: weather-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-weather
  template:
    metadata:
      labels:
        app: weather-weather
    spec:
      containers:
        - name: weatherweather-container
          image: aliahmed312/weatherapp-weather:latest
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 5000
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

          env:
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: api-key
          
