apiVersion: v1
kind: Service
metadata:
  name: weather-weather-service
spec:
  type: ClusterIP
  selector:
    app: weather-weather
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP
    name: http

    